"""
PredatorEye Web App
Accepts uploaded scan JSON from the local agent,
runs analysis server-side, and serves a shareable HTML report.
"""

import sys
import os
import uuid
import json
import datetime
import threading
import time

from flask import (
    Flask, render_template, request,
    jsonify, send_from_directory, abort, redirect, url_for
)

# Allow importing from the parent project directory
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from analyzers import RiskScorer, AttackPathAnalyzer
from predictors import PathPredictor
from prevention import RecommendationEngine
from reports import HTMLReporter

# ── App setup ────────────────────────────────────────────────────────────────
app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 5 * 1024 * 1024   # 5 MB upload limit

REPORTS_DIR   = os.path.join(os.path.dirname(__file__), "reports")
REPORT_TTL_H  = 24          # delete reports older than this many hours
os.makedirs(REPORTS_DIR, exist_ok=True)

# Simple in-memory stats counter
_stats = {"total_scans": 0}


# ── Background cleanup ───────────────────────────────────────────────────────
def _cleanup_loop():
    while True:
        time.sleep(3600)
        cutoff = datetime.datetime.now() - datetime.timedelta(hours=REPORT_TTL_H)
        for fname in os.listdir(REPORTS_DIR):
            fpath = os.path.join(REPORTS_DIR, fname)
            try:
                mtime = datetime.datetime.fromtimestamp(os.path.getmtime(fpath))
                if mtime < cutoff:
                    os.remove(fpath)
            except Exception:
                pass

threading.Thread(target=_cleanup_loop, daemon=True).start()


# ── Routes ───────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("index.html", stats=_stats)


@app.route("/scan")
def scan():
    return render_template("scan.html")


@app.route("/api/analyze", methods=["POST"])
def analyze():
    """
    Accepts a JSON file upload (the output from the local agent),
    runs the full analysis pipeline, saves an HTML report, and
    returns the report URL.
    """
    # ── Accept upload ────────────────────────────────────────────────────────
    if "file" not in request.files:
        return jsonify({"error": "No file uploaded. Upload the scan_results.json from your device."}), 400

    f = request.files["file"]
    if not f.filename.endswith(".json"):
        return jsonify({"error": "Only .json files are accepted."}), 400

    try:
        raw = f.read(5 * 1024 * 1024)  # read up to 5 MB
        scan_results = json.loads(raw)
    except Exception:
        return jsonify({"error": "Invalid JSON file. Make sure you upload the file generated by the PredatorEye agent."}), 400

    if not isinstance(scan_results, dict):
        return jsonify({"error": "Unexpected JSON format."}), 400

    # ── Run analysis ─────────────────────────────────────────────────────────
    try:
        findings     = RiskScorer(scan_results).score()
        attack_paths = AttackPathAnalyzer(findings).analyze()
        prediction   = PathPredictor(findings, attack_paths).predict()
        recs         = RecommendationEngine(findings).generate()
    except Exception as e:
        return jsonify({"error": f"Analysis failed: {str(e)}"}), 500

    # ── Generate HTML report ─────────────────────────────────────────────────
    report_id  = str(uuid.uuid4()).replace("-", "")[:16]
    html_path  = os.path.join(REPORTS_DIR, f"{report_id}.html")

    try:
        HTMLReporter(prediction, findings, recs, scan_results).write(html_path)
    except Exception as e:
        return jsonify({"error": f"Report generation failed: {str(e)}"}), 500

    _stats["total_scans"] += 1

    return jsonify({
        "report_id":  report_id,
        "report_url": url_for("view_report", report_id=report_id, _external=True),
        "risk_level": prediction.get("risk_level"),
        "risk_score": prediction.get("overall_score"),
        "findings":   prediction.get("total_findings"),
    })


@app.route("/report/<report_id>")
def view_report(report_id):
    # Sanitise ID — only alphanumeric
    if not report_id.isalnum() or len(report_id) > 32:
        abort(404)
    html_path = os.path.join(REPORTS_DIR, f"{report_id}.html")
    if not os.path.exists(html_path):
        return render_template("expired.html"), 404
    return send_from_directory(REPORTS_DIR, f"{report_id}.html")


@app.route("/download/agent")
def download_agent():
    agent_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "agent.py")
    return send_from_directory(
        os.path.dirname(agent_path),
        "agent.py",
        as_attachment=True,
        download_name="predatoreye-agent.py",
    )


# ── Run ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
